name: Build firmware
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PlatformIO project
        uses: karniv00l/platformio-run-action@v1
        with:
          project-dir: firmware
          environments: digispark-tiny
          disable-auto-clean: true

      - name: Make and upload release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            firmware/.pio/build/digispark-tiny/firmware.hex
            firmware/.pio/build/digispark-tiny/firmware.elf
