name: Build PlatformIO project
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          project-dir: ./firmware
          silent: false
          verbose: true
          disable-auto-clean: false
